version : '3'
service :
  train :
    image : fg12345/trainservice.latest
    ports :
      - "80:80"
    deploy :
      replicas : '3'

  movies :
    image: fg12345/moviesservice.latest
    ports :
      - "81:80"
    deploy :
      replicas : '3'

  dth :
    image : fg12345/dthservice.latest
    ports :
      - "82:80"
    deploy :
      replicas : '3'

  recharge :
    image : fg12345/rechargeservice.latest
    ports :
      - "83:80"
    deploy :
      replicas : '3'
